version: '3'
services:
  twin-webserver:
    build: 
      context: .
      dockerfile: Dockerfile.test
    image: "dt-instance-webserver"
    depends_on:
      - scylla-db
      - scylla-manager
    environment: 
      - RUST_LOG=info
      - SERVER_ADDRESS=0.0.0.0:8080
      - DB_ADDRESS=scylla-db:9042
      - SECRET_KEY=Xqv8jTGLxT
      - TWIN_INSTANCE=38162cb0-e585-43d7-b55d-5c240b2bfb7c
    networks:
      - default
    volumes:
      - .:/tmp/dt-instance-webserver
  scylla-manager:
    image: scylladb/scylla-manager
    container_name: scylla-manager
    depends_on:
      - scylla-db
    networks:
      - default
    links:
      - "scylla-db:scylla-manager-db"
  scylla-db:
    image: scylladb/scylla
    container_name: scylla-db
    expose: [9042]
    networks:
      - default
networks:
  default:
