
version: 2

jobs:
  build:
    docker:
      - image: circleci/rust:1.44
    steps:
      - checkout
      - run:
          name: Pull submodules
          command: git submodule init; git submodule update --remote
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v4-rust-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all targets
          command: cargo build --all --all-targets
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v4-rust-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - setup_remote_docker
      - run:
          name: Build compose containers
          command: docker-compose -f docker-compose.test.yml up -d --build
      - run:
          name: Wait and init DB.
          command: sleep 60; docker exec -it scylla-db cqlsh --file '/home/circleci/project/shared/db/db.cql'
      - run:
          name: Run tests inside restart container
          command: docker restart dt-instance-webserver_twin-webserver_1; docker exec -it dt-instance-webserver_twin-webserver_1 cargo test --all
