name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker-compose -f docker-compose.test.yml up -d  
      - name: Wait and init DB.
        run: sleep 60; docker exec -it scylla-db cqlsh -f /db/db.cql; docker exec -it scylla-db cqlsh -f /db/init.cql
      - name: Run tests inside restart container
        run: docker container ls; docker restart dt-instance-webserver-webserver_1; docker exec -it dt-instance-webserver-webserver_1 cargo test --all
